version: 2
updates:
  ### update non aws packages daily
  # package.json in root directory
  - package-ecosystem: "npm"
    directory: "/"
    # daily at 5am UTC
    schedule:
      interval: "daily"
    # always get latest version
    versioning-strategy: increase
    # set reviewers
    reviewers:
      - "kbrashears5"
    ignore:
      - dependency: "aws*"
        
  ### update aws packages weekly
  # package.json in root directory
  - package-ecosystem: "npm"
    directory: "/"
    # weekly on monday at 5am UTC
    schedule:
      interval: "weekly"
    # always get latest version
    versioning-strategy: increase
    # set reviewers
    reviewers:
      - "kbrashears5"
    allow:
      - dependency: "aws*"